### ISSUE TITLE
有模型国内下载地址吗

### ISSUE THREAD

**Issue by Mr-IT007** [baichuan-inc/Baichuan2#77]
有模型国内下载地址吗

**Comment by bc-gpd** [comment]
可以尝试从[modelscope](https://modelscope.cn/organization/baichuan-inc)下载

**Comment by MurraryZhao** [comment]
> 可以尝试从[modelscope](https://modelscope.cn/organization/baichuan-inc)下载

模型下载经常中断：
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/baichuan-inc/Baichuan2-7B-Base/repo?Revision=v1.0.1&FilePath=pytorch_model-00001-of-00002.bin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fde113f3bb0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Downloading:   5%|███████████▊                                                                                                                                                                                                                                | 474M/9.25G [04:21<1:22:36, 1.90MB/s]

**Comment by Mr-IT007** [comment]
git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git

**Comment by MurraryZhao** [comment]
> git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git

好的，我试下

**Comment by MurraryZhao** [comment]
> git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git

您下载成功了嘛，我还是会卡在下载模型阶段。其他的文件都能正常下载。

**Comment by Mr-IT007** [comment]
> > git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git
> 
> 您下载成功了嘛，我还是会卡在下载模型阶段。其他的文件都能正常下载。

我是可以的

**Comment by MurraryZhao** [comment]
> > > git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git
> > 
> > 
> > 您下载成功了嘛，我还是会卡在下载模型阶段。其他的文件都能正常下载。
> 
> 我是可以的

好吧，我再尝试下，谢谢。

**Comment by cristianohello** [comment]
git clone https://www.modelscope.cn/baichuan-inc/Baichuan2-13B-Chat-4bits.git
Cloning into 'Baichuan2-13B-Chat-4bits'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 51 (delta 18), reused 38 (delta 12), pack-reused 0
Unpacking objects: 100% (51/51), done.
